### ISSUE TITLE
ok guys i need help making multiple websites for the same github pages site

### ISSUE THREAD

**Issue by Decotron99** [Ayducc-Games/Schoolgrounds#3]
i want there to be a website at: ayducc-games.github.io/Schoolgrounds
and one at schoolgroundshtml.tk
and one a schoolgrounds.free
thanks a lot for the help :)

**Comment by PiSaucer** [comment]
Can you please allow firebase to have access so I can add those domains? Also, I have access to settings to allow the GitHub domain to work again?

**Comment by Decotron99** [comment]
how do i allow firebase to work?

**Comment by PiSaucer** [comment]
> You need to go to your profile settings -> Applications -> "Authorized OAuth Apps" tab -> Click on Firebase CLI -> Organization access will appear below, just guarantee access

[https://github.com/firebase/firebase-tools/issues/3143#issuecomment-780857654](https://github.com/firebase/firebase-tools/issues/3143#issuecomment-780857654)

**Comment by Decotron99** [comment]
ok so now we need to make it so there is schoolgrounds.tk and ayducc-games.github.io/Schoolgrounds and schoolgrounds.free

**Comment by PiSaucer** [comment]
Ok, as of now we have multiple domains:
- [schoolgrounds.herokuapp.com](https://schoolgrounds.herokuapp.com/)
- [schoolgroundshtml.tk](https://schoolgroundshtml.tk/)
- [schoolgrounds.web.app](https://schoolgrounds.web.app/)
- [schoolgrounds.firebaseapp.com](https://schoolgrounds.firebaseapp.com/)
- [schoolground.ml](https://schoolground.ml/)
- [schoolground.tk](https://schoolground.tk/)

**Comment by Decotron99** [comment]
ok cool
