### ISSUE TITLE
PISAUCER PLEASE ADD THIS

### ISSUE THREAD

**Issue by Decotron99** [Ayducc-Games/Schoolgrounds#7]
https://github.com/Decotron99/nintendrust-entertainment-system

**Comment by PiSaucer** [comment]
Done

**Comment by Decotron99** [comment]
it dosent work

**Comment by PiSaucer** [comment]
Ok I will look at it later

**Comment by Decotron99** [comment]
i think u had the wrong html file i changed it imma see if it works

**Comment by Decotron99** [comment]
ok i fixed it
